version: '3.8'

services:
  frontend:
    container_name: poker_frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    container_name: poker_backend
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://poker:poker@db:5432/poker
    depends_on:
      - db

  db:
    container_name: poker_db
    image: postgres:15
    environment:
      - POSTGRES_USER=poker
      - POSTGRES_PASSWORD=poker
      - POSTGRES_DB=poker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
