import { applyMove, getPossibleMoves, State } from './game';

const state = State.gameInitializedState();

console.log("initial", state)
console.log("valid moves", getPossibleMoves(state))
console.log(applyMove(state, "c"))
console.log("valid moves", getPossibleMoves(state))
console.log(applyMove(state, "c"))
console.log("valid moves", getPossibleMoves(state))
console.log(applyMove(state, "c"))
console.log("valid moves", getPossibleMoves(state))
console.log(applyMove(state, "f"))
console.log("valid moves", getPossibleMoves(state))
console.log(applyMove(state, "c"))
console.log("valid moves", getPossibleMoves(state))
console.log(applyMove(state, "c"))
console.log("valid moves", getPossibleMoves(state))
console.log(applyMove(state, "c"))
console.log("valid moves", getPossibleMoves(state))
console.log(applyMove(state, "x"))
console.log("valid moves", getPossibleMoves(state))
console.log(applyMove(state, "x"))
console.log("valid moves", getPossibleMoves(state))
console.log(applyMove(state, "x"))
console.log("valid moves", getPossibleMoves(state))
console.log(applyMove(state, "x"))
console.log("valid moves", getPossibleMoves(state))
console.log(applyMove(state, "x"))
console.log("valid moves", getPossibleMoves(state))